version: '3'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: wurstmeister/kafka
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  userpublisher:
    build: ./ProducerPublisher
    container_name: userpublisher
    depends_on:
      - broker
    environment:
      #SPRING_PROFILES_ACTIVE: 'production'
      KAFKA_TOPIC: 'users'
      KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'

  userpersistence:
    build: ./UserPersistence
    container_name: userpersistence
    depends_on:
      - broker
    ports:
      - "8181:8080"
    environment:
      #SPRING_PROFILES_ACTIVE: 'production'
      KAFKA_NOTIFICATION_TOPIC: 'notifications'
      KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'

  userlistener:
    build: ./UserRestListener
    container_name: userlistener
    depends_on:
      - broker
    ports:
      - "8282:8080"
    environment:
      #SPRING_PROFILES_ACTIVE: 'production'
      KAFKA_TOPIC: 'users'
      KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'

  notifications:
    build: ./NotificationPersistence
    container_name: notifications
    depends_on:
      - broker
    ports:
      - "8383:8080"
    environment:
      #SPRING_PROFILES_ACTIVE: 'production'
      DEVTIRO_KAFKA_TOPIC: 'notifications'
      KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'
  