apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationpersistence
  labels:
    app: notificationpersistence
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notificationpersistence
  template:
    metadata:
      labels:
        app: notificationpersistence
    spec:
      containers:
      - name: notificationpersistence
        image: samaan7/kafka-microservice:1.0
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "broker:29092"
