apiVersion: apps/v1
kind: Deployment
metadata:
  name: userpersistence
  labels:
    app: userpersistence
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userpersistence
  template:
    metadata:
      labels:
        app: userpersistence
    spec:
      containers:
      - name: userpersistence
        image: samaan7/kafka-microservice:1.0
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "broker:29092"
