apiVersion: apps/v1
kind: Deployment
metadata:
  name: userlistener
  labels:
    app: userlistener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userlistener
  template:
    metadata:
      labels:
        app: userlistener
    spec:
      containers:
      - name: userlistener
        image: samaan7/kafka-microservice:4.1
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "broker:9092"
