apiVersion: v1
kind: Service
metadata:
  name: notificationpersistenceservice
  labels:
    app: notificationpersistenceservice
spec:
  selector:
    app: notificationpersistence
  ports:
    - protocol: TCP
      port: 8383
      targetPort: 8080