apiVersion: v1
kind: Service
metadata:
  name: userlistenerservice
  labels:
    app: userlistenerservice
spec:
  selector:
    app: userlistener
  ports:
    - protocol: TCP
      port: 8282
      targetPort: 8080