apiVersion: v1
kind: Service
metadata:
  name: userpersistenceservice
  labels:
    app: userpersistenceservice
spec:
  selector:
    app: userpersistence
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8080